:sectnums:
:sectnumlevels: 2
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]


:toc:
:toclevels: 1

= Boom (with kernel parameters)

== Overview

Boom is a boot manager for Linux systems that support the 'BootLoader Specification' (BLS).  

In short, boom:

  * simplifies creation of new or modified boot entries
  * includes a set of Python libraries and a command line tool
  * does not modify the existing boot loader configuration
  * *only inserts* additional entries

The objectives of this exercise are quite simple:

  * familiarize yourself with the basics of creating and mangaging boot entries
  * create an customized alternative boot entry to load a detectable kernel parameter

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd_exec}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-boom-checkhost.sh
----

You are now ready to proceed with these exercises.



== Core Concepts

The Boom system uses a concept of "profiles" and "entries" to allow templated configurations to be cloned and modified.  This minimizes the need for the user to input complex boot parameters manually for each iteration of the configuration.

So we begin with the management of boom profiles.



=== Profile

==== List / Show

Just for reference, let's take a look at this systems existing profiles.  There could be many, or in some cases none.

[{format_cmd_exec}]
----
boom profile list
----

[{format_plane}]
----
sID    Name                            OsVersion
----

For a more detailed view, you can use the `profile show` sub-command.

[{format_cmd_exec}]
----
boom profile show
----



==== Create

Creating a profile is handled by a simple command.  However determining all of th various parameters
can be challeging and are outside the scope of this lab.  Thus we have prepared a simple script to do the hard work.

[{format_cmd_exec}]
----
workshop-boom-mkprofile.sh
----

[{format_plane}]
----
Determining root device...
Creating default BOOM profile

Created profile with os_id 52f9e46:
  OS ID: "52f9e46e9c9bfe3066102f23d6dafa819978b375",
  Name: "Red Hat Enterprise Linux", Short name: "rhel",
  Version: "9.2 (Plow)", Version ID: "9.2",
  Kernel pattern: "/vmlinuz-%{version}", Initramfs pattern: "/initramfs-%{version}.img",
  Root options (LVM2): "rd.lvm.lv=%{lvm_root_lv}",
  Root options (BTRFS): "rootflags=%{btrfs_subvolume}",
  Options: "root=%{root_device} ro %{root_opts}",
  Title: "%{os_name} %{os_version_id} (%{version})",
  Optional keys: "grub_users grub_arg grub_class id", UTS release pattern: "el9"
----

NOTE: In this example, the root disk is identified by a UUID.  As a result, `boom` will incorrectly identify the paths to the kernel and initiramfs when creating the grub entry.  To avoid this current problem (bug?), we tweak the boom profile to add `/boot` to the paths.



==== Inspect

Verify that the boom profile was created by the previous command:

[{format_cmd_exec}]
----
boom profile list --osversion "9.2 (Plow)"
----

[{format_cmd_output}]
----
OsID    Name                     OsVersion
52f9e46 Red Hat Enterprise Linux 9.2 (Plow)
----

And for a more detailed view:

[{format_cmd_exec}]
----
boom profile show --osversion "9.2 (Plow)"
----

[{format_cmd_output}]
----
OS Profile (os_id=52f9e46)
  OS ID: "52f9e46e9c9bfe3066102f23d6dafa819978b375",
  Name: "Red Hat Enterprise Linux", Short name: "rhel",
  Version: "9.2 (Plow)", Version ID: "9.2",
  Kernel pattern: "/vmlinuz-%{version}", Initramfs pattern: "/initramfs-%{version}.img",
  Root options (LVM2): "rd.lvm.lv=%{lvm_root_lv}",
  Root options (BTRFS): "rootflags=%{btrfs_subvolume}",
  Options: "root=%{root_device} ro %{root_opts}",
  Title: "%{os_name} %{os_version_id} (%{version})",
  Optional keys: "grub_users grub_arg grub_class id", UTS release pattern: "el9"
----


=== Boot Entry

Now it is time to create a boot entry for grub which utilizes the same 
boot environment as the current system, but with a few added kernel parameters.



==== List / Show

Before we do any work, let's take a quick look at what exists already.

[{format_cmd_exec}]
----
boom entry list
----

[{format_cmd_output}]
----
BootID  Version                      Name                     RootDevice
a482bbd 5.14.0-284.30.1.el9_2.x86_64 Red Hat Enterprise Linux UUID=016e7284-31f6-4c28-bbb1-98c5b25fcdbf
----

And for a more detailed view

[{format_cmd_exec}]
----
boom entry show
----

[{format_cmd_output}]
----
Boot Entry (boot_id=a482bbd)
  title Red Hat Enterprise Linux (5.14.0-284.30.1.el9_2.x86_64) 9.2 (Plow)
  version 5.14.0-284.30.1.el9_2.x86_64
  linux /vmlinuz-5.14.0-284.30.1.el9_2.x86_64
  initrd /initramfs-5.14.0-284.30.1.el9_2.x86_64.img $tuned_initrd
  options root=UUID=016e7284-31f6-4c28-bbb1-98c5b25fcdbf console=ttyS0,115200n8 console=tty0 net.ifnames=0 rd.blacklist=nouveau nvme_core.io_timeout=4294967295 crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M $tuned_params
  grub_users $grub_users
  grub_arg --unrestricted
  grub_class rhel
----



==== Create

First we need to determine the root device.  We can do this by inspecting the current kernel's boot commandline.

[{format_cmd_exec}]
----
cat /proc/cmdline
----

[{format_cmd_output}]
----
BOOT_IMAGE=(hd0,gpt3)/vmlinuz-5.14.0-284.30.1.el9_2.x86_64 root=UUID=016e7284-31f6-4c28-bbb1-98c5b25fcdbf console=ttyS0,115200n8 console=tty0 net.ifnames=0 rd.blacklist=nouveau nvme_core.io_timeout=4294967295 crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M
----

We can further isolate the undesired parameters with a simple grep.

[{format_cmd_exec}]
----
grep -o '\broot=[^ ]*' /proc/cmdline
----

[{format_cmd_output}]
----
root=UUID=016e7284-31f6-4c28-bbb1-98c5b25fcdbf
----

NOTE: In this scenario, the boot device is listed by a UUID.  Depending on the lab environment, you could see a logical volume name or a physcial device path.

Now we need to get to the actual device (or lvm) path.  Although this logic is not complicated, it's not really the focus of this exercise, so you've been provided another workshop-script.

[{format_cmd_exec}]
----
workshop-boom-mkentry.sh
----

[{format_cmd_output}]
----
Determining root device...
UUID reduction if necessary...
Creating GRUB2 entry...

DEBUG: boom create --title 'RHEL 9 Workshop' --root-device /dev/nvme0n1p4

Created entry with boot_id 4b36f16:
  title RHEL 9 Workshop
  machine-id ec2486de3bb2e99bbb39853600f8317b
  version 5.14.0-284.30.1.el9_2.x86_64
  linux /vmlinuz-5.14.0-284.30.1.el9_2.x86_64
  initrd /initramfs-5.14.0-284.30.1.el9_2.x86_64.img
  options root=/dev/nvme0n1p4 ro
  grub_users $grub_users
  grub_arg --unrestricted
  grub_class kernel
----



==== Inspect

Take a look at currently configured boom-boot entries.

[{format_cmd_exec}]
----
boom entry list
----

[{format_cmd_output}]
----
BootID  Version                      Name                     RootDevice
a482bbd 5.14.0-284.30.1.el9_2.x86_64 Red Hat Enterprise Linux UUID=016e7284-31f6-4c28-bbb1-98c5b25fcdbf
4b36f16 5.14.0-284.30.1.el9_2.x86_64 Red Hat Enterprise Linux /dev/nvme0n1p4
----

Show details about our boom-boot entry.

[{format_cmd_exec}]
----
export BOOM_BOOTID=$(boom entry list --title "RHEL 9 Workshop" -o bootid,title | grep -m 1 Workshop | awk '{print $1}')
boom entry show $BOOM_BOOTID
----

[{format_cmd_output}]
----
Boot Entry (boot_id=4b36f16)
  title RHEL 9 Workshop
  machine-id ec2486de3bb2e99bbb39853600f8317b
  version 5.14.0-284.30.1.el9_2.x86_64
  linux /vmlinuz-5.14.0-284.30.1.el9_2.x86_64
  initrd /initramfs-5.14.0-284.30.1.el9_2.x86_64.img
  options root=/dev/nvme0n1p4 ro
  grub_users $grub_users
  grub_arg --unrestricted
  grub_class kernel
----



==== Delete 

[{format_cmd_exec}]
----
export BOOM_BOOTID=$(boom entry list --title "RHEL 9 Workshop" -o bootid,title | grep -m 1 Workshop | awk '{print $1}')
boom entry delete $BOOM_BOOTID
----




== Exercise: Custom Kernel Options

=== Profile

The profile we will use was created during the Core Concepts exercise above.  
Let's take a look at the details to confirm everthing is in order.

[{format_cmd_exec}]
----
boom profile show --osversion "9.2 (Plow)"
----

[{format_cmd_output}]
----
OS Profile (os_id=52f9e46)
  OS ID: "52f9e46e9c9bfe3066102f23d6dafa819978b375",
  Name: "Red Hat Enterprise Linux", Short name: "rhel",
  Version: "9.2 (Plow)", Version ID: "9.2",
  Kernel pattern: "/vmlinuz-%{version}", Initramfs pattern: "/initramfs-%{version}.img",
  Root options (LVM2): "rd.lvm.lv=%{lvm_root_lv}",
  Root options (BTRFS): "rootflags=%{btrfs_subvolume}",
  Options: "root=%{root_device} ro %{root_opts}",
  Title: "%{os_name} %{os_version_id} (%{version})",
  Optional keys: "grub_users grub_arg grub_class id", UTS release pattern: "el9"
----



=== Boot Entry

Again, to avoid some of the complexities considered outside the scope this lab we will
run a prepared script to configure the boot entry.

[{format_cmd_exec}]
----
workshop-boom-mkentry-custom.sh
----

[{format_cmd_output}]
----
Determining root device...
UUID reduction if necessary...
Creating GRUB2 entry...

DEBUG: boom create --title 'RHEL 9 Workshop' --root-device /dev/nvme0n1p4 -a custom_value=true

Created entry with boot_id ffe2f1e:
  title RHEL 9 Workshop
  machine-id ec2486de3bb2e99bbb39853600f8317b
  version 5.14.0-284.30.1.el9_2.x86_64
  linux /vmlinuz-5.14.0-284.30.1.el9_2.x86_64
  initrd /initramfs-5.14.0-284.30.1.el9_2.x86_64.img
  options root=/dev/nvme0n1p4 ro custom_value=true
  grub_users $grub_users
  grub_arg --unrestricted
  grub_class kernel
----

Notice in the options that we slipped in the `custom_value=true`.



=== GRUB: Set Default Entry

WARNING: If possible, bring up the virtual machine console for node3 before proceeding.  

Before reboot, there are 2 options to invoke the right loader at restart:
  . enter the GRUB menu at startup and select at boot time
  . use grub-set-default to pre-select which one to load by default
  
We are going to opt for pre-select since it's easier to script.  Use the following workshop to inspect 
the currently configured GRUB menu options.

[{format_cmd_exec}]
----
workshop-boom-grublist.sh
----

[{format_cmd_output}]
----
     0  title="Red Hat Enterprise Linux (5.14.0-284.30.1.el9_2.x86_64) 9.2 (Plow)"
     1  title="RHEL 9 Workshop"
----

Let us now inspect the GRUB configuration for `RHEL 9 Workshop`.  The following 
complicated command figures out the index on your system.

[{format_cmd_exec}]
----
grubby --info=$(workshop-boom-grublist.sh | grep -m1 "Workshop" | awk '{print $1}')
----

[{format_cmd_output}]
----
index=1
kernel="/boot/vmlinuz-5.14.0-284.30.1.el9_2.x86_64"
args="ro custom_value=true"
root="/dev/nvme0n1p4"
initrd="/boot/initramfs-5.14.0-284.30.1.el9_2.x86_64.img"
title="RHEL 9 Workshop"
id="ec2486de3bb2e99bbb39853600f8317b-ffe2f1e-5.14.0-284.30.1.el9_2.x86_64"
----

WARNING: *DO NOT PROCEED* unless both `kernel=` and `initrd=` include the path `/boot/<filename>`.

We want to reboot to our "RHEL 9 Workshop", so we need to isolate and use the "index" from above.

[{format_cmd_exec}]
----
eval $(grubby --info=$(workshop-boom-grublist.sh | grep -m1 "Workshop" | awk '{print $1}')| grep index)
grub2-set-default $index
----



=== Inspect

Verify that the parameters stuck.  Notice that "saved_entry=1", that's what we want.

[{format_cmd_exec}]
----
grub2-editenv list
----

[{format_cmd_output}]
----
saved_entry=1
boot_success=1
----



=== Reboot

We will now reset our host and boot with the alternate kernel arguments.

[{format_cmd_exec}]
----
reboot
----



=== Validate

Once the host is back online, ssh to back to `node3` and verify that the alternate kernel parameters are active.

[{format_cmd_exec}]
----
ssh node3
----

[{format_cmd_exec}]
----
cat /proc/cmdline
----

[{format_cmd_output}]
----
BOOT_IMAGE=(hd0,gpt3)/vmlinuz-5.14.0-70.13.1.el9_0.x86_64 root=/dev/nvme0n1p4 ro custom_value=true
----

Confirm that the custom key-value is now part of the kernel boot options.



== Conclusion

Wahoo! You are done.  If you have any questions, please ask.

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec}]
----
workshop-finish-exercise.sh
----



== Additional Resources

  * link:https://github.com/bmr-cymru/boom[Boom project page] 
  * link:https://github.com/bmr-cymru/snapshot-boot-docs[Boot to snapshot documentation] 
  * link:https://systemd.io/BOOT_LOADER_SPECIFICATION[BootLoader Specification] 
  * link:https://www.sourceware.org/lvm2/[LVM2 resource page] 
  * link:http://sources.redhat.com/dm/[Device-mapper resource page] 

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

