:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]


:toc:
:toclevels: 1

= Boom (with kernel parameters)

== Overview

BOOM is a boot manager for Linux systems that support the 'BootLoader Specification' for boot entry configuration. It simplifies the creation of new or modified boot entries: for example, to boot snapshot images of the system created using LVM.

BOOM does not modify the existing boot loader configuration, and *only inserts* additional entries. The existing configuration is maintained, and any distribution integration, such as kernel installation and update scripts, continue to function as before.

BOOM also has a simple command-line interface (CLI) and API.

The object of this exercise is quite simple.  We are going to create an alternative boot entry which 
will load the same kernel with a few additional detectable parameters.

== Getting Started

For these exercises, you will be using the host `node3` as user `root`.

From host `bastion`, ssh to `node3`.

[{format_cmd_exec}]
----
ssh node3
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-boom-checkhost.sh
----

You are now ready to proceed with these exercises.

== Installation

The following set of instructions will install Boom.

[{format_cmd_exec}]
----
dnf install -y boom-boot
----

That was easy!


== Overview

=== Create a Profile

Creating a new boot entry begins with a boom `profile`.

[{format_cmd_exec}]
----
workshop-boom-mkprofile.sh
----

[{format_plane}]
----
Determining root device...
Creating default BOOM profile

Created profile with os_id e0ef3eb:
  OS ID: "e0ef3ebf3862de64e4082062f0063422796dcca6",
  Name: "Red Hat Enterprise Linux", Short name: "rhel",
  Version: "9.0 (Plow)", Version ID: "9.0",
  Kernel pattern: "/vmlinuz-%{version}", Initramfs pattern: "/initramfs-%{version}.img",
  Root options (LVM2): "rd.lvm.lv=%{lvm_root_lv}",
  Root options (BTRFS): "rootflags=%{btrfs_subvolume}",
  Options: "root=%{root_device} ro %{root_opts}",
  Title: "%{os_name} %{os_version_id} (%{version})",
  Optional keys: "", UTS release pattern: "el9"
----

NOTE: In this example, the root disk is identified by a UUID.  As a result, `boom` will incorrectly identify the paths to the kernel and initiramfs when creating the grub entry.  To avoid this current problem (bug?), we tweak the boom profile to add `/boot` to the paths.

[NOTE]
====
_Native command(s) to make boom profile_
[{format_cmd_output}]
----
boom profile create --from-host --uname-pattern el9 --kernel-pattern="/boot/vmlinuz-%{version}" --initramfs-pattern="/boot/initramfs-%{version}.img"
----
====


=== Inpect a Profile

Verify that the boom profile was created by the previous command.

[{format_cmd_exec}]
----
boom profile list --osversion "9.0 (Plow)"
----

[{format_cmd_output}]
----
OsID    Name                     OsVersion
e0ef3eb Red Hat Enterprise Linux 9.0 (Plow)
----

=== Create GRUB Entry

Now to create a boot entry for grub which utilizes the same boot environment as the current system, but with a few
added kernel parameters.

==== Determine Root Device

First we need to determine the root device.  We can do this by inspecting the current kernel's boot commandline.

[{format_cmd_exec}]
----
cat /proc/cmdline
----

[{format_cmd_output}]
----
BOOT_IMAGE=(hd0,gpt3)/vmlinuz-5.14.0-70.13.1.el9_0.x86_64 root=UUID=2af18441-b487-4dac-9729-2c12f5adc6ed console=ttyS0,115200n8 console=tty0 net.ifnames=0 rd.blacklist=nouveau nvme_core.io_timeout=4294967295 crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M
----

We can further isolate the undesired parameters with a simple grep.

[{format_cmd_exec}]
----
grep -o '\broot=[^ ]*' /proc/cmdline
----

[{format_cmd_output}]
----
root=UUID=f7614c41-2835-4125-bb13-50772dc2f30c
----

NOTE: In this scenario, the boot device is listed by a UUID.  Depending on the lab environment, you could see a logical volume name or a physcial device path.


==== Create Entry

Now we need to get to the actual device (or lvm) path.  Although this logic is not complicated, it's not really the focus of this exercise, so you've been provided another workshop-script.

[{format_cmd_exec}]
----
workshop-boom-mkentry.sh
----

[{format_cmd_output}]
----
Determining root device...
UUID reduction if necessary...
Creating GRUB2 entry...

DEBUG: boom create --title 'RHEL 9 Workshop' --root-device /dev/nvme0n1p4

WARNING - Options for BootEntry(boot_id=0d96d09) do not match OsProfile: marking read-only
Created entry with boot_id ed93f0f:
  title RHEL 9 Workshop
  machine-id ec2e0c92349d906c08af3ffadd95217f
  version 5.14.0-70.13.1.el9_0.x86_64
  linux /vmlinuz-5.14.0-70.13.1.el9_0.x86_64
  initrd /initramfs-5.14.0-70.13.1.el9_0.x86_64.img
  options root=/dev/nvme0n1p4 ro
----

[NOTE]
====
_Native command(s) to make grub entry_
[{format_cmd_output}]
----
# For LVM base root
boom create --title "RHEL 9 Workshop" --rootlv <VG>/<LV>

# For block device base root
boom create --title "RHEL 9 Workshop" --root-device <ROOT-DEVICE>
----
====


==== Inspect Entries

Take a look at currently configured boom-boot entries.

[{format_cmd_exec}]
----
boom entry list
----

[{format_cmd_output}]
----
WARNING - Options for BootEntry(boot_id=0d96d09) do not match OsProfile: marking read-only
BootID  Version                     Name                     RootDevice
0d96d09 5.14.0-70.13.1.el9_0.x86_64 Red Hat Enterprise Linux UUID=2af18441-b487-4dac-9729-2c12f5adc6ed
ed93f0f 5.14.0-70.13.1.el9_0.x86_64 Red Hat Enterprise Linux /dev/nvme0n1p4
----

Show details about our boom-boot entry.

[{format_cmd_exec}]
----
export BOOM_BOOTID=$(boom entry list --title "RHEL 9 Workshop" -o bootid,title | grep Workshop | awk '{print $1}')
boom entry show $BOOM_BOOTID
----

[{format_cmd_output}]
----
Boot Entry (boot_id=ed93f0f)
  title RHEL 9 Workshop
  machine-id ec2e0c92349d906c08af3ffadd95217f
  version 5.14.0-70.13.1.el9_0.x86_64
  linux /vmlinuz-5.14.0-70.13.1.el9_0.x86_64
  initrd /initramfs-5.14.0-70.13.1.el9_0.x86_64.img
  options root=/dev/nvme0n1p4 ro
----

==== Delete Grub Entry

[{format_cmd_exec}]
----
export BOOM_BOOTID=$(boom entry list --title "RHEL 9 Workshop" -o bootid,title | grep Workshop | awk '{print $1}')
boom entry delete $BOOM_BOOTID
----




== Custom Boot Options

=== Create Grub Entry

[{format_cmd_exec}]
----
workshop-boom-mkentry-custom.sh
----

[{format_cmd_output}]
----
Determining root device...
UUID reduction if necessary...
Creating GRUB2 entry...

DEBUG: boom create --title 'RHEL 9 Workshop' --root-device /dev/vda1 -a custom_value=true

WARNING - Boom grub2 integration is disabled in '/boot/../etc/default/boom'
Created entry with boot_id a07736e:
  title RHEL 9 Workshop
  machine-id 4739d97a827c41e2a71d911afb7941af
  version 4.18.0-147.el8.x86_64
  linux /vmlinuz-4.18.0-147.el8.x86_64
  initrd /initramfs-4.18.0-147.el8.x86_64.img
  options root=/dev/vda1 ro custom_value=true
----

Notice in the options that we slipped in the `custom_value=true`.

=== Set Next Boot to Custom Entry

WARNING: If possible, bring up the virtual machine console for node3 before proceeding.  

Before reboot, there are 2 options to invoke the right loader at restart:
  . enter the GRUB menu and select at boot time
  . use grub-set-default to pre-select which one to load by default
  
We are going to opt for pre-select since it's easier to script.  Use the following workshop to inspect 
the currently configured GRUB menu options.

[{format_cmd_exec}]
----
workshop-boom-grublist.sh
----

[{format_cmd_output}]
----
     0  title="Red Hat Enterprise Linux (4.18.0-147.el8.x86_64) 8.1 (Ootpa)"
     1  title="RHEL 9 Workshop"
----

Let us now inspect the GRUB configuration for `RHEL 9 Workshop`, which in this example is entry #1. 

[{format_cmd_exec}]
----
grubby --info=1
----

[{format_cmd_output}]
----
index=2
kernel="/boot/vmlinuz-4.18.0-147.el8.x86_64"
args="ro custom_value=true"
root="/dev/vda1"
initrd="/boot/initramfs-4.18.0-147.el8.x86_64.img"
title="RHEL 9 Workshop"
id="44d81e936d7e445797933e8cbc199cea-b8f0549-4.18.0-147.el8.x86_64"
----

WARNING: *DO NOT PROCEED TO REBOOT* unless both `kernel=` and `initrd=` include the path `/boot/<filename>`.

We want to reboot to our "RHEL 9 Workshop", so again in this example the entry is #1.

[{format_cmd_exec}]
----
grub2-set-default 1
----


=== Inspect

Verify that the parameters stuck.  Notice that "saved_entry=1", that's what we want.

[{format_cmd_exec}]
----
grub2-editenv list
----

[{format_cmd_output}]
----
saved_entry=1
kernelopts=root=/dev/mapper/rhel-root_snapshot ro crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet
boot_success=0
----


=== Reboot

We will now reset our host and boot with the alternate kernel arguments.

[{format_cmd_exec}]
----
reboot
----



=== Validate

Once the host is back online, ssh to back to `node3` and verify that the alternate kernel parameters are active.

[{format_cmd_exec}]
----
ssh node3
----

[{format_cmd_exec}]
----
cat /proc/cmdline
----

[{format_cmd_output}]
----

----

Confirm that the custom key-value is now part of the kernel boot options.



== Conclusion

Wahoo! You are done.  If you have any questions, please ask.

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec2}]
----
workshop-finish-exercise.sh
----



== Additional Resources

  * link:https://github.com/bmr-cymru/boom[Boom project page] 
  * link:https://github.com/bmr-cymru/snapshot-boot-docs[Boot to snapshot documentation] 
  * link:https://systemd.io/BOOT_LOADER_SPECIFICATION[BootLoader Specification] 
  * link:https://www.sourceware.org/lvm2/[LVM2 resource page] 
  * link:http://sources.redhat.com/dm/[Device-mapper resource page] 

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

