:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]


:toc:
:toclevels: 1

= Kernel Live Patching - Plan your reboots!

WARNING: This unit requires an active entitlement for RHEL and registration with the Red Hat CDN (subscription-manager).  If connected to a Red Hat Satellite server, the Satellite must also have synchronized content to match the release of RHEL used for this workshop.  So, besides overall functionality being impacted ... some variations in the output can also be expected.


== Overview

Red Hat Enterprise Linux offers kernel live patching, a solution to patch your running kernel without rebooting or restarting any processes. In this lab, we'll explore this solution, which ships in the form of "kpatches" that can be managed with the "kpatch" tool.

== Getting Started

For these exercises, you will be using the host `node2` as user `root`.

From host `bastion`, ssh to `node2`.

[{format_cmd_exec}]
----
ssh node2
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-kpatch-checkhost.sh
----

You are now ready to proceed with these exercises.

== Installing a kpatch

Let's start by looking at the current kernel version:

[{format_cmd_exec}]
----
rpm -q kernel
----

[{format_cmd_output}]
----
kernel-5.14.0-162.23.1.el9_1.x86_64
----

[{format_cmd_exec}]
----
uname -r
----

[{format_cmd_output}]
----
5.14.0-162.23.1.el9_1.x86_64
----

Here we can see that we are running the 5.14.0-162.23.1.el9_1.x86_64 kernel. Now we install all kpatches for our kernel:

[{format_cmd_exec}]
----
dnf install "kpatch-patch = $(uname -r)" -y
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)                                                                 7.0 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                                              8.9 kB/s | 2.8 kB     00:00
Dependencies resolved.
======================================================================================================================================================
 Package                                      Architecture           Version                      Repository                                     Size
======================================================================================================================================================
Installing:
 kpatch-patch-5_14_0-162_23_1                 x86_64                 0-0.el9_1                    rhel-9-for-x86_64-baseos-rpms                 7.8 k
Installing dependencies:
 kpatch                                       noarch                 0.9.4-3.el9                  rhel-9-for-x86_64-baseos-rpms                  16 k
Installing weak dependencies:
 kpatch-dnf                                   noarch                 0.4-3.el9                    rhel-9-for-x86_64-baseos-rpms                  18 k

Transaction Summary
======================================================================================================================================================
Install  3 Packages

Total download size: 42 k
Installed size: 33 k
...<SNIP>...
----

Note that kpatches are cumulative, so you cannot pick and choose a specific set of patches. You must take all fixes shipped by kpatches. At this time, kpatches are limited to security vulnerabilities. For a list of which kpatches are available and which vulnerabilities they address by CVE, please see: <https://access.redhat.com/articles/4499631>

Further, if you'd like to look at which CVEs are included by the kpatch installed on the system, you can do:

[{format_cmd_exec}]
----
rpm -q --changelog kpatch-patch-5_14_0-162_23_1-0-0.el9_1.x86_64
----

[{format_cmd_output}]
----
* Fri Mar 24 2023 Yannick Cote <ycote@redhat.com> [0-0.el9]
- An empty patch to subscribe to kpatch stream for kernel-5.14.0-162.23.1.el9_1 [2181596]
----

Well that's a pretty lame example, but the reality is that at this point in time the running kernel does not have any issued kpatches.

So let's just look some older output from a similar command that inspected the kpatches for a RHEL 9.0 kernel (kernel-5.14.0-70.13.1.el9_0).

[{format_cmd_output}]
----
* Wed Jun 22 2022 Joe Lawrence <joe.lawrence@redhat.com> [1-1.el9_0]
- kernel: Small table perturb size in the TCP source port generation algorithm can lead to information leak [2087132] {CVE-
2022-1012}
- kernel: a use-after-free write in the netfilter subsystem can lead to privilege escalation to root [2093170] {CVE-2022-1966}
- kernel: buffer overflow in IPsec ESP transformation code [2087138] {CVE-2022-27666}

* Mon May 02 2022 Yannick Cote <ycote@redhat.com> [0-0.el9]
- An empty patch to subscribe to kpatch stream for kernel-5.14.0-70.13.1.el9_0 [2081116]
----

This tells us that the kpatch (kernel-5.14.0-70.13.1.el9_0) protected against CVE-2021-3501.

Let's check `kpatch list`:

[{format_cmd_exec}]
----
kpatch list
----

[{format_cmd_output}]
----
* Fri Mar 24 2023 Yannick Cote <ycote@redhat.com> [0-0.el9]
- An empty patch to subscribe to kpatch stream for kernel-5.14.0-162.23.1.el9_1 [2181596]

[root@node2 ~]# kpatch list
Loaded patch modules:

Installed patch modules:
----

Again, a pretty lame example.  Let's again look back in time at the output for the kpatches on kernel kernel-5.14.0-70.13.1.el9_0.

[{format_cmd_output}]
----
Loaded patch modules:
kpatch_5_14_0_70_13_1_1_1 [enabled]

Installed patch modules:
kpatch_5_14_0_70_13_1_1_1 (5.14.0-70.13.1.el9_0.x86_64)
----

We can see that kpatch_5_14_0_70_13_1_1_1 was installed and loaded. These protections are effective immediately and without having to reboot. We could now schedule a reboot for a time that is convenient for you. 

== Taking that Scheduled Reboot 

Kernel live patching is all about letting you schedule your reboots and not having to take downtime. We aren't actually going to reboot our lab machines, but I'd like to spend a moment discussing what happens when you reboot.

If you reboot without installing a new kernel, you will boot back into the default kernel and if that one has kpatches, they will get loaded. Effectively, this means that your kpatch stack will persist.

If you do update the kernel prior to rebooting, on the next reboot, you'll boot into the default kernel (which is now the new one) and thus your regularly running kernel should have the needed fixes without having any kpatches enabled.

WARNING:  For the sake of this workshop and potential impact to other exercises that might use this node, we will skip installing a new kernel and rebooting.

== Conclusion

This concludes the exercises related to kpatch.

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec}]
----
workshop-finish-exercise.sh
----



== Additional Resources

  * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/999999999/html/kernel_administration_guide/applying_patches_with_kernel_live_patching[Applying Patches with Kernel Live Patching]
  
[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

