:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]


:toc:
:toclevels: 1

= Upgrading from RHEL 8 to RHEL 9

WARNING: THIS UNIT IS A WORK IN PROGRESS AND NOT COMPLETE

== Overview

WARNING:  This unit will only function if the workshop environment is provisioned with a local Satellite Server OR if the client is registered to redhat.com.  Please consult the instructor for directions before proceeding.

In this unit, we will get familiar with the upgrade tool called LEAPP.

== Getting Started

For these exercises, you will be using the host `leapp` as user `root`.  Before you begin, confirm the node was provisioned with RHEL 8.6

From host `bastion`, ssh to `leapp`.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh leapp*
----

Use `sudo` to elevate your privileges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Verify that you are on the right host for these exercises.

[bash,options="nowrap",subs="{markup-in-source}"]
----
# *workshop-leapp-checkhost.sh*
----

== Current RHEL Version Verification

Verify through a few commands that this is currently running RHEL8.  These will show the current version of RHEL, the version of the running kernel and the rpm repos available to the system.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
cat /etc/redhat-release
----

[{format_cmd_output}]
----
Red Hat Enterprise Linux release 8.6 (Ootpa)
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
uname -r
----

[{format_cmd_output}]
----
4.18.0-372.9.1.el8.x86_64
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum repolist
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
repo id                                    repo name
rhel-8-for-x86_64-appstream-rpms           Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms              Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
rhel-8-for-x86_64-supplementary-rpms       Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)----
----

You are now ready to proceed with the exercises.

== Host Preparation

NOTE: The steps listed here are for reference outside of this workshop only.  None of these steps need to be performed for the exercise to function.

=== Package Repositories

First item of business is to ensure the proper software repositories are enabled on the host.  In our workshop environment, the leapp host was likely provisioned with a RHEL 8.x ISO image and configured with local static self-managed repos.

If necessary, begin by disabling any local static repos and switching to the latest managed ones from Red Hat.

WARNING: You can probably skip this step if you can connect to a Satellite or directly to redhat.com.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum-config-manager --disable my-rhel-8-server-rpm-repo

----

Next, register the host and attach an entitlement.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
subscription-manager register --auto-attach

----

Finally, enable all of the correct software repositories.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
subscription-manager repos --disable=*
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
subscription-manager repos --enable=rhel-8-for-x86_64-baseos-rpms --enable=rhel-8-for-x86_64-appstream-rpms
----

Ensure that Red Hat Subscription Manager is set to consume the latest RHEL 8 content.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
subscription-manager release --unset
----

If you use the yum-plugin-versionlock plug-in to lock packages to a specific version, clear the lock as follows.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum versionlock clear
----

== LEAPP Installation

=== LEAPP Tools
Install the LEAPP tools and any dependencies

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
yum install -y leapp-upgrade

----

=== LEAPP Data

Delete any results from any possible previous attempts to run leapp

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
rm -rf /root/tmp_leapp_py3
----

== LEAPP Local Files for Disconnected Upgrade

=== Package Repositories

There are several files needed to complete the upgrade that are available online, which are not accessible if the system is not able to access the internet (see link at bottom of exercise).  For this workshop, the following command will put them where they need to go:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
cd /etc/leapp/files
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
tar -xzvf /usr/local/share/leapp-data17.tar.gz
----

== LEAPP Pre-Upgrade

Now run the preupgrade option to generate a preliminary report to see if there are any issues found that could prevent the upgrade from proceeding smoothly.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
leapp preupgrade
----

== Pre-Upgrade Report

The output from the previous command should have listed a few items that are inhibiting the upgrade of the host.

[{format_cmd_output}]
----
=================================================
                     UPGRADE INHIBITED
=================================================


Debug output written to /var/log/leapp/leapp-preupgrade.log

=================================================
                           REPORT
=================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

=================================================
                       END OF REPORT
=================================================

Answerfile has been generated at /var/log/leapp/answerfile

----

Notice that the output refers you to the pre-upgrade report for details and remediations.  If your system has the cockpit-leapp package installed, you can switch to using a web-broswer to step through each item and inspect the remediation options.

Look at the first several lines of the report mentioned above, /var/log/leapp/leapp-report.txt

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
head /var/log/leapp/leapp-report.txt
----

The first two lines indicate a Risk Factor, in this case high/inhibitor meaning that this issue will prevent the upgrade from proceeding.  Followed by a Summary of the issue:

[{format_cmd_output}]
----
Summary: Firewalld has enabled configuration option "AllowZoneDrifiting" which has been removed in RHEL-9. New behavior is as if "AllowZoneDrifiting" was set to "no".
----

This tells us that there is a Firewalld configuration that was allowed in RHEL8 that is no longer allowed in RHEL9.  The next line tells us a "hint" at how to remediate the issue so that the upgrade can proceed:

[{format_cmd_output}]
----
Remediation: [hint] Set AllowZoneDrifting=no in /etc/firewalld/firewalld.conf
----

And the following line gives an actual command that can be used to make the change without having to edit the file directly:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
sed -i "s/^AllowZoneDrifting=.*/AllowZoneDrifting=no/" /etc/firewalld/firewalld.conf
----

Now re-run the preupgrade, this time there should be no inhibitors

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
leapp preupgrade
----

This time we expect the output to come back clean without any inhibitors that would prevent the upgrade.

[source,options="nowrap",subs="{markup-in-source}"]
----

=================================================
                           REPORT
=================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

=================================================
                       END OF REPORT
=================================================

Answerfile has been generated at /var/log/leapp/answerfile
----

== LEAPP Upgrade

Everything should be ready to run the upgrade.  This will install several rpms, make some repo and other configuration changes, and will take several minutes (6 to 10 in our vm testing).  

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
leapp upgrade
----

After several minutes (5 - 8) you should see an almost identical report output indicating that phase one of the upgrade has completed

[{format_cmd_output}]
----

=================================================
                           REPORT
=================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

=================================================
                       END OF REPORT
=================================================

Answerfile has been generated at /var/log/leapp/answerfile
----

And that a reboot is now required for the upgrade to proceed.  Without console access you won't be able to see the final steps of the upgrade.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
# reboot
----

[{format_cmd_output}]
----
Connection to leapp closed by remote host.
Connection to leapp closed.
----

after another 7 - 10 minutes, you should be able to ssh back in from the bastion host

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *ssh leapp*
----

Use `sudo` to elevate your privileges.

[bash,options="nowrap",subs="{markup-in-source}"]
----
$ *sudo -i*
----

Finally, re-run the commands from earlier to verify that the leapp node has actually been upgraded to RHEL9

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
cat /etc/redhat-release
----

[{format_cmd_output}]
----
Red Hat Enterprise Linux release 9.0 (Plow)
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
uname -r
----

[{format_cmd_output}]
----
5.14.0-70.17.1.el9_0.x86_64
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
dnf repolist
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
repo id                                    repo name
rhel-9-for-x86_64-appstream-rpms           Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
rhel-9-for-x86_64-baseos-rpms              Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
rhel-9-for-x86_64-supplementary-rpms       Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)
----


== Summary


[discrete]
== Additional Reference Materials

* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/upgrading_from_rhel_8_to_rhel_9/index[UPGRADING FROM RHEL 7 TO RHEL 8]
* link:https://access.redhat.com/articles/3664871[Data required by the Leapp utility for a disconnected RHEL in-place upgrade]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
