:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


:toc:
:toclevels: 1

= Introduction to systemd

== Overview

Systemd is the "init" system for RHEL 9 (and 8 and 7 for that matter).  Long ago it replaced Upstart, the SysV "init" system used in releases of RHEL 6.x and older.  Systemd is more than just a facility to bring up user space, it is a system manager that offers:

  * service parallelization
  * socket and D-Bus activation
  * on-demand starting of services
  * track services and child processes via cgroups
  * and much more

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `bastion`, ssh to `node1`.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*ssh node1*
----

Use `sudo` to elevate your priviledges.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*sudo -i*
----

Verify that you are on the right host for these exercises.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*workshop-systemd-checkhost.sh*
----

You are now ready to proceed with these exercises.

== Analyzing System Startup

Let's collect some initial data about the boot process

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemd-analyze*
----

[source,options="nowrap",subs="{markup-in-source}"]
----
Startup finished in 1.806s (kernel) + 3.082s (initrd) + 8.596s (userspace) = 13.485s
multi-user.target reached after 7.129s in userspace
----

Next let's inspect further details about all running units, ordered by the time they took to initialize. 

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemd-analyze blame | head -n 15*
----

[source,options="nowrap",subs="{markup-in-source}"]
----
2.407s initrd-switch-root.service
1.657s cloud-init-local.service
1.560s dnf-makecache.service
1.538s kdump.service
1.021s cloud-init.service
 802ms cloud-config.service
 795ms cloud-final.service
 750ms tuned.service
 572ms dracut-initqueue.service
 433ms dev-hugepages.mount
 367ms dev-mqueue.mount
 366ms firewalld.service
 359ms sys-kernel-debug.mount
 353ms sys-kernel-tracing.mount
 345ms kmod-static-nodes.service
 322ms NetworkManager-wait-online.service
 319ms modprobe@drm.service
 312ms modprobe@fuse.service
 307ms nis-domainname.service
 235ms polkit.service
----

This helps to learn the “cost” of some of the default services.  To speed up boot-time, unnecessary services could potentially be removed or disabled.

== Core Concepts

=== Units

The fundamental building block that systemd manages is called a "unit".  A "unit" can describe different types of objects, but the most common type is a "service".  

A "unit file" is the configuration file that describes a unit and tells systemd what dependencies exist and how to start, stop and monitor the object.

"unit files" are stored in 2 different directories.  One location is reserved for the default configurations as shipped by Red Hat and the other is for customization by the local administrators.

  * Red Hat unit files:    /usr/lib/systemd/system/...
  * Customizations:        /etc/systemd/system/...

=== Targets
systemd has a concept similar to SysV init runlevels, called targets.  systemd will boot to the “default target” which can be configured using the systemctl set-default command.  Some common targets and their equivalent SysV runlevels are:

  * multi-user.target == runlevel 3
  * graphical.target == runlevel 5

Let's view the current default target.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl get-default*
----

[bash,options="nowrap"]
----
multi-user.target
----

=== Services
As mentioned above, systemd has another concept called a service.  A service is a type of unit which defines the traditional daemon or process.  Now let us look at what services are running on the system:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl -t service*
----

[bash,options="nowrap"]
----
UNIT                               LOAD   ACTIVE SUB     DESCRIPTION
auditd.service                     loaded active running Security Auditing Service
chronyd.service                    loaded active running NTP client/server
crond.service                      loaded active running Command Scheduler
dbus-broker.service                loaded active running D-Bus System Message Bus
dracut-shutdown.service            loaded active exited  Restore /run/initramfs on shutdown
firewalld.service                  loaded active running firewalld - dynamic firewall daemon
...<output truncated>...
----

Next let's view all of the services available (ie: everything installed, running or not) on the system. The following command is similar to the older chkconfig --list as it will show both enabled and disabled services:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl list-unit-files -t service*
----

[bash,options="nowrap"]
----
UNIT FILE                                  STATE           VENDOR PRESET
auditd.service                             enabled         enabled
autovt@.service                            alias           -
blk-availability.service                   disabled        disabled
chrony-wait.service                        disabled        disabled
chronyd.service                            enabled         enabled
...<output truncated>...
----

The state will  be enabled, disabled, static, or masked.  Static indicates that the unit file does not contain an "install" section used to enable the unit.  In this case, the unit typically performs a one-off action or is used as a dependency of another unit and should not be run by itself.

== Example : LAMP Stack

=== Install Packages

Now that we have a good idea of what’s installed on our system, let’s get a basic lamp stack up and running.  If you prefer not to type all of these commands, there is a workshop script below to save you some time.

Let us install some packages.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*yum install -y httpd mariadb-server mariadb*
----

[bash,options="nowrap"]
----
...snip ...
Package httpd-2.4.51-7.el9_0.x86_64 is already installed.
Package mariadb-server-3:10.5.13-2.el9.x86_64 is already installed.
Package mariadb-3:10.5.13-2.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
----

=== Enable Services

Now it's time to enable the relevant system services.

NOTE: The "enable --now" syntax was introduced in a recent release of RHEL 7 and of course is now availbale in RHEL 8 and RHEL 9.  The option permanently enables AND immediately starts the specified services in a single command.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl enable --now httpd mariadb*
----

[bash,options="nowrap"]
----
Created symlink /etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service.
Created symlink /etc/systemd/system/mysql.service → /usr/lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/mysqld.service → /usr/lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /usr/lib/systemd/system/mariadb.service.
----

Now let's check the status.  You should see two separate sections in the output, one for httpd and one for mariadb.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl status httpd mariadb*
----

[bash,options="nowrap"]
----
● httpd.service - The Apache HTTP Server
     Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-06-07 15:47:46 EDT; 31s ago
       Docs: man:httpd.service(8)
   Main PID: 37396 (httpd)
     Status: "Total requests: 0; Idle/Busy workers 100/0;Requests/sec: 0; Bytes served/sec:   0 B/sec"
      Tasks: 213 (limit: 22918)
     Memory: 23.0M
        CPU: 65ms
     CGroup: /system.slice/httpd.service
             ├─37396 /usr/sbin/httpd -DFOREGROUND
             ├─37445 /usr/sbin/httpd -DFOREGROUND
...<output truncated>...
----

=== Enable Firewall

Last but not least, you need to enable a firewall port.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*firewall-cmd --add-service=http*
----

[bash,options="nowrap"]
----
success
----

So as promised, here is a workshop script that performs all of the above steps.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*workshop-systemd-lamp.sh*
----

=== Customize Services

systemd controls more than daemons or services. For this lab, we will primarily be working with service units but it's important to know that systemd is handling the dependencies between other types: sockets, timers, mounts, swap, slices, etc.

Unit files are stored in one of three places:

  * '/usr/lib/systemd/system' - default configs that ship with the RHEL and are updated by regular maintenance
  * '/etc/systemd/system' - custom configs that persist and replace (or augment) default configs
  * '/run/systemd/system' - runtime changes that won't persist

While the defaults for unit files won’t need to be altered most of the time, there will be circumstances where changing the defaults is quite beneficial. These could include hardware or software watchdog monitoring, tunings, resource management, or many other reasons.

Create a drop-in configuration file to extend the default httpd.service unit

==== Modify httpd

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*workshop-systemd-httpdconfig.sh*
----

[bash,options="nowrap"]
----
Contents of /etc/systemd/system/httpd.service.d/50-httpd.conf
[Service]
Restart=always
OOMScoreAdjust=-1000
----

OOMScoreAdjust is used by the Kernel's Out Of Memory killer and is an  integer between -1000 (to disable OOM killing for this process) and 1000 (to make killing of this process under memory pressure very likely).  

Notify systemd of the changes.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl daemon-reload*
----

==== Modify mariadb

Similar to what you did in the last step, extend the mariadb.service unit with Restart=always. 

This time we'll use systemctl to create the drop-in and notify systemd of the changes.

`systemctl edit` allows inserting the content for the drop-in and also handles the `systemctl daemon-reload` automatically.

.[root@node1]#
[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
# *systemctl edit mariadb*
----

.Type the following using the editor:
[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
[Service]
Restart=always
----

Save and quit the editor, and view the unit

`systemctl cat` is a quick and easy way to view the contents of a unit & and it's drop-ins.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl cat mariadb*
----

[bash,options="nowrap"]
----
...snip...
# Restart crashed server only, on-failure would also restart, for example, when
# my.cnf contains unknown option
Restart=on-abort
RestartSec=5s

UMask=007

# Give a reasonable amount of time for the server to start up/shut down
TimeoutSec=300

# Place temp files in a secure directory, not /tmp
PrivateTmp=true

# /etc/systemd/system/mariadb.service.d/override.conf
[Service]
Restart=always
----

=== Verify

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl status httpd*
----

[bash,options="nowrap"]
----
● httpd.service - The Apache HTTP Server
     Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/httpd.service.d
             └─50-httpd.conf
     Active: active (running) since Tue 2022-06-07 15:47:46 EDT; 5min ago
       Docs: man:httpd.service(8)
   Main PID: 37396 (httpd)
     Status: "Total requests: 0; Idle/Busy workers 100/0;Requests/sec: 0; Bytes served/sec:   0 B/sec"
      Tasks: 213 (limit: 22918)
     Memory: 23.0M
        CPU: 181ms
     CGroup: /system.slice/httpd.service
             ├─37396 /usr/sbin/httpd -DFOREGROUND
             ├─37445 /usr/sbin/httpd -DFOREGROUND
----

Notice that systemctl status displays that the unit has been extended with a drop-in file.


[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*systemctl status mariadb*
----

[bash,options="nowrap"]
----
● mariadb.service - MariaDB 10.5 database server
     Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/mariadb.service.d
             └─override.conf
     Active: active (running) since Tue 2022-06-07 15:47:48 EDT; 6min ago
       Docs: man:mariadbd(8)
             https://mariadb.com/kb/en/library/systemd/
   Main PID: 37717 (mariadbd)
     Status: "Taking your SQL requests now..."
      Tasks: 8 (limit: 22918)
     Memory: 73.2M
        CPU: 337ms
     CGroup: /system.slice/mariadb.service
             └─37717 /usr/libexec/mariadbd --basedir=/usr
----

== Additional Resources

Red Hat Documentation

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_basic_system_settings/introduction-to-systemd_configuring-basic-system-settings[Introduction to systemd]
    

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
