:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
:format_plain: bash,options="nowrap"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]



:toc:
:toclevels: 1

= Introduction to systemd

== Overview

Systemd is the "init" system for RHEL 9 (and 8 and 7 for that matter).  Long ago it replaced Upstart, the SysV "init" system used in releases of RHEL 6.x and older.  Systemd is more than just a facility to bring up user space, it is a system manager that offers:

  * service parallelization
  * socket and D-Bus activation
  * on-demand starting of services
  * track services and child processes via cgroups
  * and much more

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `bastion`, ssh to `node1`.

[{format_cmd_exec}]
----
ssh node1
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-systemd-checkhost.sh
----

You are now ready to proceed with these exercises.

== Core Concepts

=== Units

The fundamental building block that systemd manages is called a "unit".  A "unit" can describe different types of objects, but the most common type is a "service".  

A "unit file" is the configuration file that describes a unit and tells systemd what dependencies exist and how to start, stop and monitor the object.

"unit files" are stored in 2 different directories.  One location is reserved for the default configurations as shipped by Red Hat and the other is for customization by the local administrators.

  * Red Hat unit files:    /usr/lib/systemd/system/...
  * Customizations:        /etc/systemd/system/...

=== Targets
systemd has a concept similar to SysV init runlevels, called targets.  systemd will boot to the “default target” which can be configured using the systemctl set-default command.  Some common targets and their equivalent SysV runlevels are:

  * multi-user.target == runlevel 3
  * graphical.target == runlevel 5

Let's view the current default target.

[{format_cmd_exec}]
----
systemctl get-default
----

[{format_cmd_output}]
----
multi-user.target
----

=== Services
As mentioned above, systemd has another concept called a service.  A service is a type of unit which defines the traditional daemon or process.  Now let us look at what services are running on the system:

[{format_cmd_exec}]
----
systemctl -t service | head -n 15
----

[{format_cmd_output}]
----
UNIT                               LOAD   ACTIVE SUB     DESCRIPTION
auditd.service                     loaded active running Security Auditing Service
chronyd.service                    loaded active running NTP client/server
cloud-config.service               loaded active exited  Apply the settings specified in cloud-config
cloud-final.service                loaded active exited  Execute cloud user/final scripts
cloud-init-local.service           loaded active exited  Initial cloud-init job (pre-networking)
cloud-init.service                 loaded active exited  Initial cloud-init job (metadata service crawler)
crond.service                      loaded active running Command Scheduler
dbus-broker.service                loaded active running D-Bus System Message Bus
dracut-shutdown.service            loaded active exited  Restore /run/initramfs on shutdown
firewalld.service                  loaded active running firewalld - dynamic firewall daemon
getty@tty1.service                 loaded active running Getty on tty1
import-state.service               loaded active exited  Import network configuration from initramfs
irqbalance.service                 loaded active running irqbalance daemon
kdump.service                      loaded active exited  Crash recovery kernel arming
----

Next let's view all of the services available (ie: everything installed, running or not) on the system. The following command is similar to the older chkconfig --list as it will show both enabled and disabled services:

[{format_cmd_exec}]
----
systemctl --no-pager list-unit-files -t service
----

[{format_cmd_output}]
----
UNIT FILE                                  STATE           VENDOR PRESET
auditd.service                             enabled         enabled
autovt@.service                            alias           -
chrony-wait.service                        disabled        disabled
chronyd.service                            enabled         enabled
cloud-config.service                       enabled         disabled
cloud-final.service                        enabled         disabled
cloud-init-local.service                   enabled         disabled
cloud-init.service                         enabled         disabled
cockpit-motd.service                       static          -
cockpit-wsinstance-http.service            static          -
cockpit-wsinstance-https-factory@.service  static          -
cockpit-wsinstance-https@.service          static          -
cockpit.service                            static          -
console-getty.service                      disabled        disabled
container-getty@.service                   static          -

...<output truncated>...
----

The state will  be enabled, disabled, static, or masked.  Static indicates that the unit file does not contain an "install" section used to enable the unit.  In this case, the unit typically performs a one-off action or is used as a dependency of another unit and should not be run by itself.



== Analyzing System Startup

Let's collect some initial data about the boot process

[{format_cmd_exec}]
----
systemd-analyze
----

[{format_cmd_output}]
----
Startup finished in 2.463s (kernel) + 3.527s (initrd) + 22.967s (userspace) = 28.957s
multi-user.target reached after 8.257s in userspace.
----

Next let's inspect further details about all running units, ordered by the time they took to initialize.

[{format_cmd_exec}]
----
systemd-analyze blame | head -n 15
----

[{format_cmd_output}]
----
14.897s kdump.service
 5.793s sys-devices-platform-serial8250-tty-ttyS2.device
 5.793s dev-ttyS2.device
 5.792s dev-ttyS3.device
 5.792s sys-devices-platform-serial8250-tty-ttyS3.device
 5.787s dev-ttyS0.device
 5.787s sys-devices-pnp0-00:04-tty-ttyS0.device
 5.778s dev-ttyS1.device
 5.778s sys-devices-platform-serial8250-tty-ttyS1.device
 5.756s sys-module-configfs.device
 5.558s dev-disk-by\x2did-nvme\x2dAmazon_Elastic_Block_Store_vol0a6e8f9e6b883a484\x2dpart2.device
 5.558s dev-disk-by\x2dpartuuid-68b2905b\x2ddf3e\x2d4fb3\x2d80fa\x2d49d1e773aa33.device
 5.558s dev-disk-by\x2duuid-7B77\x2d95E7.device
 5.558s dev-disk-by\x2did-nvme\x2dnvme.1d0f\x2d766f6c3061366538663965366238383361343834\x2d416d617a6f6e20456c617374696320426c6f
636b2053746f7265\x2d00000001\x2dpart2.device
 5.558s dev-disk-by\x2dpath-pci\x2d0000:00:04.0\x2dnvme\x2d1\x2dpart2.device
----

This helps to learn the “cost” of some of the default services.  To speed up boot-time, unnecessary services could potentially be removed or disabled.


== Exercise : Install a LAMP Stack

=== Install Packages

Now that we have a good idea of what’s installed on our system, let’s get a basic lamp stack up and running.

Let us install some packages.

[{format_cmd_exec}]
----
dnf install -y httpd mariadb-server mariadb
----

[{format_cmd_output}]
----
...snip ...
Package httpd-2.4.53-11.el9_2.5.x86_64 is already installed.
Package mariadb-server-3:10.5.16-2.el9_0.x86_64 is already installed.
Package mariadb-3:10.5.16-2.el9_0.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
----

=== Enable Services

Now it's time to enable the relevant system services.

NOTE: The "enable --now" syntax was introduced in a recent release of RHEL 7 and of course is now availbale in RHEL 8 and RHEL 9.  The option permanently enables AND immediately starts the specified services in a single command.

[{format_cmd_exec}]
----
systemctl enable --now httpd mariadb
----

[{format_cmd_output}]
----
Created symlink /etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service.
Created symlink /etc/systemd/system/mysql.service → /usr/lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/mysqld.service → /usr/lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /usr/lib/systemd/system/mariadb.service.
----

Now let's check the status.  You should see two separate sections in the output, one for httpd and one for mariadb.

[{format_cmd_exec}]
----
systemctl --no-pager status httpd mariadb
----

[{format_cmd_output}]
----
● httpd.service - The Apache HTTP Server
     Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; preset: disabled)
     Active: active (running) since Mon 2023-09-25 14:53:46 UTC; 11s ago
       Docs: man:httpd.service(8)
   Main PID: 36188 (httpd)
     Status: "Total requests: 0; Idle/Busy workers 100/0;Requests/sec: 0; Bytes served/sec:   0 B/sec"
      Tasks: 213 (limit: 22480)
     Memory: 33.3M
        CPU: 105ms
     CGroup: /system.slice/httpd.service
             ├─36188 /usr/sbin/httpd -DFOREGROUND
             ├─36233 /usr/sbin/httpd -DFOREGROUND
             ├─36238 /usr/sbin/httpd -DFOREGROUND
             ├─36239 /usr/sbin/httpd -DFOREGROUND
             └─36252 /usr/sbin/httpd -DFOREGROUND
...<output truncated>...
----

=== Enable Firewall

Last but not least, you need to enable a firewall port.

[{format_cmd_exec}]
----
firewall-cmd --add-service=http
----

[{format_cmd_output}]
----
success
----



== Exercise: Customize Default Services

systemd controls more than daemons or services. For this lab, we will primarily be working with service units but it's important to know that systemd is handling the dependencies between other types: sockets, timers, mounts, swap, slices, etc.

Unit files are stored in one of three places:

  * '/usr/lib/systemd/system' - default configs that ship with the RHEL and are updated by regular maintenance
  * '/etc/systemd/system' - custom configs that persist and replace (or augment) default configs
  * '/run/systemd/system' - runtime changes that won't persist

While the defaults for unit files won’t need to be altered most of the time, there will be circumstances where changing the defaults is quite beneficial. These could include hardware or software watchdog monitoring, tunings, resource management, or many other reasons.

Create a drop-in configuration file to extend the default httpd.service unit

=== Modify httpd

[{format_cmd_exec}]
----
workshop-systemd-httpdconfig.sh
----

[{format_cmd_output}]
Contents of /etc/systemd/system/httpd.service.d/50-httpd.conf
----
[Service]
Restart=always
OOMScoreAdjust=-1000
----

OOMScoreAdjust is used by the Kernel's Out Of Memory killer and is an  integer between -1000 (to disable OOM killing for this process) and 1000 (to make killing of this process under memory pressure very likely).  

Notify systemd of the changes.

[{format_cmd_exec}]
----
systemctl daemon-reload
----

=== Modify mariadb

Similar to what you did in the last step, extend the mariadb.service unit with Restart=always. 

This time we'll use systemctl to create the drop-in and notify systemd of the changes.

`systemctl edit` allows inserting the content for the drop-in and also handles the `systemctl daemon-reload` automatically.


WARNING: You must add your service customizations BETWEEN the commented lines near the top of the template, otherwise your update will be discarded


Your edit should look like this before you save it.

[{format_plain}]
----
### Editing /etc/systemd/system/mariadb.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

[Service]
Restart=always

### Lines below this comment will be discarded
----

Proceed to make your changes now.

[{format_cmd_exec}]
----
systemctl edit mariadb
----

Type (cut & paste) the following using the automatically launched editor (vi) between the commented lines as outlined above:

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
[Service]
Restart=always
----

Save and quit the editor, and view the unit

`systemctl cat` is a quick and easy way to view the contents of a unit & and it's drop-ins.

[{format_cmd_exec}]
----
systemctl --no-pager cat mariadb
----

[{format_cmd_output}]
----
...snip...
# Restart crashed server only, on-failure would also restart, for example, when
# my.cnf contains unknown option
Restart=on-abort
RestartSec=5s

UMask=007

# Give a reasonable amount of time for the server to start up/shut down
TimeoutSec=300

# Place temp files in a secure directory, not /tmp
PrivateTmp=true

# /etc/systemd/system/mariadb.service.d/override.conf
[Service]
Restart=always
----

=== Verify

[{format_cmd_exec}]
----
systemctl --no-pager status httpd
----

[{format_cmd_output}]
----
● httpd.service - The Apache HTTP Server
     Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/httpd.service.d
             └─50-httpd.conf
     Active: active (running) since Mon 2023-09-25 14:53:46 UTC; 5min ago
       Docs: man:httpd.service(8)
   Main PID: 36188 (httpd)
     Status: "Total requests: 0; Idle/Busy workers 100/0;Requests/sec: 0; Bytes served/sec:   0 B/sec"
      Tasks: 213 (limit: 22480)
     Memory: 33.3M
        CPU: 336ms
     CGroup: /system.slice/httpd.service
             ├─36188 /usr/sbin/httpd -DFOREGROUND
             ├─36233 /usr/sbin/httpd -DFOREGROUND
             ├─36238 /usr/sbin/httpd -DFOREGROUND
             ├─36239 /usr/sbin/httpd -DFOREGROUND
             └─36252 /usr/sbin/httpd -DFOREGROUND
----

Notice that systemctl status displays that the unit has been extended with a drop-in file.

[{format_cmd_exec}]
----
systemctl --no-pager status mariadb
----

[{format_cmd_output}]
----
● mariadb.service - MariaDB 10.5 database server
     Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/mariadb.service.d
             └─override.conf
     Active: active (running) since Mon 2023-09-25 14:53:48 UTC; 6min ago
       Docs: man:mariadbd(8)
             https://mariadb.com/kb/en/library/systemd/
   Main PID: 36509 (mariadbd)
     Status: "Taking your SQL requests now..."
      Tasks: 8 (limit: 22480)
     Memory: 73.1M
        CPU: 456ms
     CGroup: /system.slice/mariadb.service
             └─36509 /usr/libexec/mariadbd --basedir=/usr
----



== Conclusion

Hopefully you should now have a fundamental understanding of how services 
are installed, managed and customized on Red Hat Enterprise Linux 9.

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec}]
----
workshop-finish-exercise.sh
----

== Additional Resources

You can find more information:

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_basic_system_settings/introduction-to-systemd_configuring-basic-system-settings[Introduction to systemd]
    

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
Verified for RHEL 9.2
////
