:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
:format_plain: bash,options="nowrap"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]


:toc:
:toclevels: 1

= Session Recording with Tlog

== Overview

Tlog is a terminal I/O recording and playback package for Linux.  The session logs retain all the passed data and timing.  Sessions are recorded in JSON format as to eventually deliver the data to a storage service _(such as Elasticsearch)_ where it can be searched, queried and be played back.

If you have successfully run the RHEL 8 lab preparation playbook, then node1.example.com has already been properly configured for session logging.  What follows are some basic exercises to demonstrate how this facility functions.

Starting with RHEL 9, TLOG is configured by a relatively simple system-role.  We will come back to that later.

== Getting Started

For these exercises, you will be using the host `node1` as user `root`.

From host `bastion`, ssh to `node1`.

[{format_cmd_exec}]
----
ssh node1
----

Use `sudo` to elevate your privileges.

[{format_cmd_exec}]
----
[[ "$UID" == 0 ]] || sudo -i
----

Verify that you are on the right host for these exercises.

[{format_cmd_exec}]
----
workshop-tlog-checkhost.sh
----

You are now ready to proceed with these exercises.

== Creating a Session Log

The system has been configured with an additional non-privileged user called `other-user`.  Run the following command to change to the `other-user`.

NOTE: The command is 'su' + 'dash' + 'other-user'.  Don't forget the dash!

[{format_cmd_exec}]
----
su - other-user
----

[{format_cmd_output}]
----
ATTENTION! Your session is being recorded!
----

You should have received a message when switching to `other-user` that the session is being recorded.

Now to do a few activities worth logging.  You can check out a directory listing, look at the host's _passwd_ and _shadow_ files.  

[{format_cmd_exec}]
----
ls -l /etc
----

[{format_cmd_output}]
----
-rw-r--r--.  1 root root       68 Apr 17 22:19 shells
drwxr-xr-x.  2 root root     4096 Apr 17 21:54 skel
-rw-r--r--.  1 root root      138 Sep 12  2019 sos.conf
drwxr-xr-x.  3 root root     4096 Apr 17 21:58 ssh
drwxr-xr-x.  2 root root     4096 Apr 17 21:55 ssl
drwx------.  4 sssd sssd     4096 Apr 17 21:55 sssd
-rw-r--r--.  1 root root       48 Apr 17 22:21 subgid
-rw-r--r--.  1 root root       24 Apr 17 22:19 subgid-
-rw-r--r--.  1 root root       48 Apr 17 22:21 subuid
-rw-r--r--.  1 root root       24 Apr 17 22:19 subuid-
-rw-r-----.  1 root root     1786 Aug 16  2019 sudo.conf
-r--r-----.  1 root root     4328 Aug 16  2019 sudoers
...SNIP...
----

[{format_cmd_exec}]
----
cat /etc/passwd
----

[{format_cmd_output}]
----
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
...SNIP...
----

[{format_cmd_exec}]
----
cat /etc/shadow
----

[{format_cmd_output}]
----
cat: /etc/shadow: Permission denied
----

Oh wait, you need root privileges to see the contents of _/etc/shadow_.  You can use sudo for that!

[{format_cmd_exec}]
----
sudo cat /etc/shadow
----

[{format_cmd_output}]
----
root:$6$9Jk5EGiB2aBl95kj$RIdiSqNdKt95zqddStFUY/zVKIUujWfGWJkLM5KQ.7zY88Kxxa0qm78qLMFRAqDO2qOrp.qZBaQAKcUFm1Is70:18370:0:99999:7:::
bin:*:17988:0:99999:7:::
daemon:*:17988:0:99999:7:::
adm:*:17988:0:99999:7:::
lp:*:17988:0:99999:7:::
sync:*:17988:0:99999:7:::
shutdown:*:17988:0:99999:7:::
halt:*:17988:0:99999:7:::
mail:*:17988:0:99999:7:::
operator:*:17988:0:99999:7:::
games:*:17988:0:99999:7:::
ftp:*:17988:0:99999:7:::
...SNIP...
----

We are done with our limited nefarious activities, so proceed to `exit`

[{format_cmd_exec}]
----
exit
----

== Session Play Back

Session logs are configured to record in the system journal by default.  A distinct advantage to this approach is that session recordings are also augmented with meta data which includes: user, session-id, host-id and a log-message-id.  Let's have a look.

[{format_cmd_exec}]
----
journalctl --no-pager -o verbose  --output-fields=TLOG_USER,TLOG_REC TLOG_USER=other-user 
----

[{format_cmd_output}]
----
Sat 2019-04-27 21:21:27.852913 EDT [s=bcde42e4c96048c3908657177414e202;i=700;b=b2333248c22a4c5f912a>
    TLOG_USER=other-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:33.354695 EDT [s=bcde42e4c96048c3908657177414e202;i=701;b=b2333248c22a4c5f912a>
    TLOG_USER=other-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:43.483301 EDT [s=bcde42e4c96048c3908657177414e202;i=702;b=b2333248c22a4c5f912a>
    TLOG_USER=other-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:54.193564 EDT [s=bcde42e4c96048c3908657177414e202;i=707;b=b2333248c22a4c5f912a>
    TLOG_USER=other-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
Sat 2019-04-27 21:21:58.770887 EDT [s=bcde42e4c96048c3908657177414e202;i=70c;b=b2333248c22a4c5f912a>
    TLOG_USER=other-user
    TLOG_REC=b2333248c22a4c5f912a245f6266582e-3cb9-e9bf9
----

Each one of those entries makes up a chunk of a session recording.  It is by way of searching the system journal and identifying the correct TLOG_REC for a specific session, that you can then play back the session using `tlog-play`.

We have taken the liberty of scripting this "search" to playback the last session log from the user other-user.
Once you hit enter on the command below, you will see a note that "Playback Started..." and again when "Playback Finished...".  
Be patient until it completes and your root prompt returns.

[{format_cmd_exec}]
----
workshop-tlog-playback.sh
----

[{format_plain}]
----
Playback Starting...
[other-user@node1 ~]$ ls -l /etc
total 1136
-rw-r--r--.  1 root root       12 Feb 24  2022 adjtime
-rw-r--r--.  1 root root     1529 Jun 23  2020 aliases
drwxr-xr-x.  2 root root     4096 Sep  4 21:04 alternatives
-rw-r--r--.  1 root root      541 Aug  9  2021 anacrontab
drwxr-xr-x.  3 root root       51 Sep  4 21:04 ansible

...<SNIP>...

setroubleshoot:!!:19239::::::
mysql:!!:19239::::::
apache:!!:19239::::::
other-user:$6$qbfI9WAi97Bpq2Cb$xGAZ90QHX3oPDF8whjame8UOTJKMFLgC2IjR5o2hm75k5PyL3cn9Hna8IpA8gt5yNP1ro0eiqAE3qsJHMVAok0:19239:0:99999:7:::
tlog:!!:19239::::::
[other-user@node1 ~]$ exit
logout

Playback Finished...
----


[NOTE]
====
_Native command(s) to playback last tlog_
----
myTLOG=`journalctl -o verbose -n 1 --output-fields=TLOG_USER,TLOG_REC TLOG_USER=other-user | grep TLOG_REC`

tlog-play -r journal -M ${myTLOG}
----
====

WARNING: It is important to wait until the playback is complete.  Do not proceed until you see the output `Playback Finished`.



== Conclusion

This concludes the exercises related to tlog.

Time to finish this unit and return the shell to it's home position.

[{format_cmd_exec}]
----
workshop-finish-exercise.sh
----



== Additional Resources

Red Hat Documentation

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/recording_sessions/getting-started-with-session-recording_getting-started-with-session-recording[Getting Started With Session Recording]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////

